export const MAX_CERTIFICATE_PDF_SIZE_MB = 20;
export const MAX_CERTIFICATE_PDF_SIZE_BYTES =
  MAX_CERTIFICATE_PDF_SIZE_MB * 1024 * 1024;

export const CERTIFICATE_PDF_SIZE_HELP_TEXT =
  `PDF only, max ${MAX_CERTIFICATE_PDF_SIZE_MB}MB`;

export const CERTIFICATE_PDF_TOO_LARGE_ERROR =
  `Certificate PDFs must be ${MAX_CERTIFICATE_PDF_SIZE_MB}MB or smaller.`;
